---
title: "SIEP - UNICEF"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
  lib_dir: libs
nature:
  highlightStyle: github
highlightLines: true
---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono"),
  header_h1_font_size = "2.0rem"
)

```


# Sinergias entre UNICEF y SIEP

- SIEP tiene como objetivo el fomento de la investigación rigurosa de cara a contribuir en las políticas públicas del país, tanto en términos de aprendizajes como en las condiciones necesarias para que todos accedan a una educación de calidad.

- No solo miramos la escuela, sino también los contextos, factores, políticas que hacen parte del entramado social (políticas sociales, protección social, infancia, etc.)

--

- SIEP reúne a investigadores de las instituciones más importantes del país

- Desde allí se puede influir positivamente en la política pública 

--

- Ambas instituciones empezando su ciclo de prioridades y acciones permite mirar en el mediano plazo


---
# Seminario

**Posibilidades**

- Seminario SIEP es un espacio consolidado de intercambio de ideas, análisis y discusión sobre políticas públicas en base a la evidencia

- Alcance regional y nacional (itinerancia en la organización)

- Asistencia nutrida formada por distintos actores: Ministerio de Educación, DRE-UGEL, docentes, estudiantes, investigadores

- Espacio para mostrar avances y hallazgos de lo que se viene haciendo y estudiando en el país

---
# Seminario

**Ruta** 

- En el marco del VIII Seminario de la SIEP (mayo 2023)

  - Concurso de tesis de Licenciatura y Maestría
  
  - Concurso de ensayos
  
- Temas:

  - Acceso, retención e integración de NNA indígenas, migrantes, con discapacidad al sistema educativo
  
  - Educación sexual integral en la secundaria
  
  - Participación y convivencia escolar

---
# Seminario

**Actividades y Recursos**

- Establecer aliados estratégicos: MINEDU, INEI, BCP, etc.
  
  - Organización
  
  - Difusión
  

---
# Producción de conocimiento en áreas relevantes para la política educativa

**Problema**

- Política educativa distante de la evidencia y del conocimiento
  
- Asuntos críticos no vienen siendo abordados con base a evidencias:
  
  - abandono escolar, migración, violencia, ESI, reforma de educación superior, educación y trabajo
  
---
# Producción de conocimiento en áreas relevantes para la política educativa

**Ruta**

- Números temáticos en Revista de la SIEP

  - Diciembre 2022: educación rural
  
  - Julio 2023: estudiantes en riesgo

  - Diciembre 2023: migración

  - Julio 2024: educación y protección social

  - Diciembre 2024: educación superior

---
# Producción de conocimiento en áreas relevantes para la política educativa

**Actividades y Recursos**

- Gestión editorial de la Revista

- Presentación de números temáticos con participación de MINEDU y otras actores

***Costo aproximado por número temático: 12,000***

---
# Fortalecimiento de la investigación entorno a poblaciones vulnerables

**Problema**

- No existe una *cultura* en la investigación de atención a aspectos éticos, especialmente en relación a poblaciones vulnerables
  
- Problemas éticos en la práctica investigativa (plagio)
  
- Hoy en día, hay un claro movimiento hacia la necesidad de establecer protocolos claros de investigación por parte de instituciones, agencias, fondos de cooperación, etc.
  
- Al lidiar con poblaciones vulnerables, el investigador se enfrenta a casos que han de recibir atención (violencia familiar, bulying, discriminación, acoso, etc.)

---
# Fortalecimiento de la investigación entorno a poblaciones vulnerables 

**Ruta**

- Creación de un ***comité interinstitucional de ética en la investigación***
  
  - Ser el referente para el país en materia de códigos de ética en investigación
      
  - Ofrecer servicios (pagados) para investigadores y universidades (lógica de sostenibilidad en el mediano plazo)
      
  - Puerta de entrada para fomento y formación de la investigación en el mundo universitario
 
---
# Fortalecimiento de la investigación entorno a poblaciones vulnerables 
     
**Actividades y Recursos**

- Secretaría técnica

  - Desarrollo de protocolos de investigación

  - Desarrollo de procedimientos del comité
  
  - Formalización y certificación
  
- Constitución de equipos de revisores

- Promoción del comité en mundo universitario

***2 años desde incepción hasta consolidación***

---
# Formación de nuevos investigadores

**Problema**

- Muy baja calidad de investigaciones de pregrado y postrado en ciencias sociales y educación
  
- Productos de investigación no elaborados para su diseminación (tesis vs artículo en revista académica)
  
--

**Ruta**

- Taller de diseminación de investigaciones producidas (objetivo: transformar tesis en artículo)

  - Enlazar convocatoria a temas de interés

  - Enlazar a presentación y concurso de tesis en Seminario

---
# Formación de nuevos investigadores

**Actividades y Recursos**

- Organización de taller
  
  - Diseño metodológico
  
  - Organización e difusión
  
- Implementación virtual (para atender a diversidad del país)
  

***Dos ciclos: 2022/2023 y 2023/2024***


---
# Movilización social: ciencia ciudadana

**Posibilidad**

- Tecnología permite desarrollo de herramientas y soluciones muy creativas

- En el mundo se vienen desarrollando eventos donde equipos multidisciplinarios desarrollan soluciones a un problema

- El problema (y las soluciones) reciben visibilidad en el ámbito público y técnico

--

**Ruta**

- Lanzar la Hackathon por la educación

  - Ejemplos: [Digieduhack](https://digieduhack.com/en/),[Science education](https://puebloscience.devpost.com/),[AI for Common Good](https://www.x5gon.org/event/hackathon/)
  
  - Enlazar a temas de interés: abandono escolar, aprendizajes, migración

---
# Movilización social: ciencia ciudadana

**Actividades y Recursos**

- Establecer aliados estratégicos: MINEDU, INEI, BCP, etc.
  
  - Organización
  
  - Difusión
  
- Implementación virtual
  

***Dos ciclos: 2023 y 2024***

---

# Talleres formativos con periodistas

**Problema**

- Los medios de comunicación tienden a presentar representaciones sociales negativas de la población migrante, indígena, o con discapacidad. En algunos casos asociando la imagen de la población migrante a actividades delincuenciales o de violencia, y en el caso de los grupos indígenas y con discapacidad con un tratamiento paternalista, infantilizada o centrada en  la pena y el sufrimiento. 

- Estas representaciones inciden en los NNA con estas características, en su formación y en las relaciones sociales que establecen con otros.

---
# Talleres formativos con periodistas 

**Ruta**

- Organización de Talleres formativos con periodistas de los departamentos (Lima, Loreto, Huancavelica, Ucayali), donde trabaja Unicef para mejorar el tratamiento informativo en base al conocimiento y evidencia, tomando en cuenta criterios de género, interculturalidad y equidad-, sobre derechos de los NNA con énfasis en el derecho a la educación
de los grupos indígenas, migrantes, con discapacidad.

---
# Talleres formativos con periodistas

**Actividades y Recursos**

  - Diseño metodológico
  
  - Organización y difusión



